export interface ThemePalette {
  id: string;
  domain: string;
  primary: string;
  primaryLight: string;
  primaryDark: string;
  accent: string;
  background: string;
  surface: string;
  text: string;
  textMuted: string;
  border: string;
}

export const themes: ThemePalette[] = [
  {
    id: 'default',
    domain: 'Navacle Standard',
    primary: '#2563EB',
    primaryLight: '#EFF6FF',
    primaryDark: '#1A3557',
    accent: '#10B981',
    background: '#F1F5F9',
    surface: '#FFFFFF',
    text: '#0F172A',
    textMuted: '#64748B',
    border: '#E2E8F0',
  },
  {
    id: 'education',
    domain: 'School / Education',
    primary: '#F59E0B',
    primaryLight: '#FEF3C7',
    primaryDark: '#B45309',
    accent: '#0284C7',
    background: '#FAFAF9',
    surface: '#FFFFFF',
    text: '#1C1917',
    textMuted: '#78716C',
    border: '#E7E5E4',
  },
  {
    id: 'healthcare',
    domain: 'Healthcare / Medical',
    primary: '#0D9488',
    primaryLight: '#F0FDFA',
    primaryDark: '#0F766E',
    accent: '#0284C7',
    background: '#F8FFFE',
    surface: '#FFFFFF',
    text: '#042F2E',
    textMuted: '#6B7280',
    border: '#CCFBF1',
  },
  {
    id: 'finance',
    domain: 'Finance / Banking',
    primary: '#047857',
    primaryLight: '#ECFDF5',
    primaryDark: '#065F46',
    accent: '#F59E0B',
    background: '#F7FFF8',
    surface: '#FFFFFF',
    text: '#022C22',
    textMuted: '#6B7280',
    border: '#D1FAE5',
  },
  {
    id: 'tech',
    domain: 'Technology / SaaS',
    primary: '#8B5CF6',
    primaryLight: '#F5F3FF',
    primaryDark: '#6D28D9',
    accent: '#14B8A6',
    background: '#FAF5FF',
    surface: '#FFFFFF',
    text: '#2E1065',
    textMuted: '#6B7280',
    border: '#E9D5FF',
  },
  {
    id: 'logistics',
    domain: 'Logistics / Transport',
    primary: '#EA580C',
    primaryLight: '#FFF7ED',
    primaryDark: '#C2410C',
    accent: '#2563EB',
    background: '#FAFAF9',
    surface: '#FFFFFF',
    text: '#1C1917',
    textMuted: '#57534E',
    border: '#FED7AA',
  },
  {
    id: 'retail',
    domain: 'Retail / E-commerce',
    primary: '#E11D48',
    primaryLight: '#FFF1F2',
    primaryDark: '#BE123C',
    accent: '#10B981',
    background: '#FFF5F7',
    surface: '#FFFFFF',
    text: '#1C1917',
    textMuted: '#78716C',
    border: '#FECDD3',
  },
  {
    id: 'realestate',
    domain: 'Real Estate / Property',
    primary: '#0369A1',
    primaryLight: '#F0F9FF',
    primaryDark: '#075985',
    accent: '#F59E0B',
    background: '#F0F9FF',
    surface: '#FFFFFF',
    text: '#0C1A2E',
    textMuted: '#64748B',
    border: '#BAE6FD',
  },
  {
    id: 'government',
    domain: 'Government / Public Sector',
    primary: '#1E3A8A',
    primaryLight: '#EFF6FF',
    primaryDark: '#1e40af',
    accent: '#DC2626',
    background: '#F8FAFF',
    surface: '#FFFFFF',
    text: '#020617',
    textMuted: '#475569',
    border: '#C7D2FE',
  },
  {
    id: 'energy',
    domain: 'Energy / Environment',
    primary: '#16A34A',
    primaryLight: '#F0FDF4',
    primaryDark: '#15803D',
    accent: '#0284C7',
    background: '#F0FDF4',
    surface: '#FFFFFF',
    text: '#052E16',
    textMuted: '#6B7280',
    border: '#BBF7D0',
  },
];
